# Explicit list of library source files.
#
# This list is intentionally explicit (no file(GLOB)) so that the installed
# target is reproducible across machines and packaging is deterministic.
# When adding or removing a source file, update this list.

set(GUILLAUME_SOURCES
    sources/application.cpp
    sources/component_registry.cpp
    sources/components/animation.cpp
    sources/components/arc.cpp
    sources/components/borders.cpp
    sources/components/bound.cpp
    sources/components/clip.cpp
    sources/components/color.cpp
    sources/components/drag_interaction.cpp
    sources/components/elevation.cpp
    sources/components/ellipse.cpp
    sources/components/focus.cpp
    sources/components/glyph.cpp
    sources/components/hand_hover_interaction.cpp
    sources/components/hand_pinch_interaction.cpp
    sources/components/hand_poke_interaction.cpp
    sources/components/hand_squeeze_interaction.cpp
    sources/components/hand_thumb_rest_interaction.cpp
    sources/components/hand_thumb_stick_interaction.cpp
    sources/components/hand_trigger_interaction.cpp
    sources/components/image.cpp
    sources/components/layout.cpp
    sources/components/line.cpp
    sources/components/model.cpp
    sources/components/mouse_hover_interaction.cpp
    sources/components/overlay.cpp
    sources/components/parent.cpp
    sources/components/range.cpp
    sources/components/ring.cpp
    sources/components/scrim.cpp
    sources/components/scrollable.cpp
    sources/components/selection.cpp
    sources/components/text.cpp
    sources/components/text_field.cpp
    sources/components/transform.cpp
    sources/components/value.cpp
    sources/ecs/component.cpp
    sources/ecs/component_registry.cpp
    sources/ecs/component_registry_filler.cpp
    sources/ecs/component_storage.cpp
    sources/ecs/component_type_id.cpp
    sources/ecs/entity.cpp
    sources/ecs/entity_builder.cpp
    sources/ecs/entity_builder_manager.cpp
    sources/ecs/entity_builder_manager_filler.cpp
    sources/ecs/entity_director.cpp
    sources/ecs/entity_director_manager.cpp
    sources/ecs/entity_director_manager_filler.cpp
    sources/ecs/entity_filler.cpp
    sources/ecs/entity_registry.cpp
    sources/ecs/entity_registry_container.cpp
    sources/ecs/level_order_traveler.cpp
    sources/ecs/parent_entity.cpp
    sources/ecs/parent_entity_filler.cpp
    sources/ecs/reverse_level_order_traveler.cpp
    sources/ecs/system.cpp
    sources/ecs/system_filler.cpp
    sources/ecs/system_phase.cpp
    sources/ecs/system_registry.cpp
    sources/entities/button.cpp
    sources/entities/button_base.cpp
    sources/entities/builder_base.cpp
    sources/entities/app_bar.cpp
    sources/entities/badge.cpp
    sources/entities/bottom_sheet.cpp
    sources/entities/card.cpp
    sources/entities/carousel.cpp
    sources/entities/checkbox.cpp
    sources/entities/chip.cpp
    sources/entities/date_picker.cpp
    sources/entities/dialog.cpp
    sources/entities/divider.cpp
    sources/entities/loading_indicator.cpp
    sources/entities/menu.cpp
    sources/entities/navigation_bar.cpp
    sources/entities/navigation_drawer.cpp
    sources/entities/navigation_rail.cpp
    sources/entities/progress_indicator.cpp
    sources/entities/search.cpp
    sources/entities/side_sheet.cpp
    sources/entities/slider.cpp
    sources/entities/segmented_button.cpp
    sources/entities/extended_floating_action_button.cpp
    sources/entities/floating_action_button.cpp
    sources/entities/floating_action_button_menu.cpp
    sources/entities/icon.cpp
    sources/entities/icon_button.cpp
    sources/entities/image.cpp
    sources/entities/list.cpp
    sources/entities/model.cpp
    sources/entities/layout.cpp
    sources/entities/radio_button.cpp
    sources/entities/snackbar.cpp
    sources/entities/split_button.cpp
    sources/entities/standard_button_group.cpp
    sources/entities/surface.cpp
    sources/entities/switch.cpp
    sources/entities/tabs.cpp
    sources/entities/text.cpp
    sources/entities/text_field.cpp
    sources/entities/time_picker.cpp
    sources/entities/toolbar.cpp
    sources/entities/tooltip.cpp
    sources/event/event_bus.cpp
    sources/event/event_manager.cpp
    sources/event/event_subscriber.cpp
    sources/event_handler.cpp
    sources/local_storage.cpp
    sources/metadata.cpp
    sources/mesh_renderable.cpp
    sources/motion/easing.cpp
    sources/scene.cpp
    sources/scene_manager.cpp
    sources/session_storage.cpp
    sources/storage.cpp
    sources/systems/animation.cpp
    sources/systems/arc_render.cpp
    sources/systems/clip.cpp
    sources/systems/drag.cpp
    sources/systems/ellipse_render.cpp
    sources/systems/elevation_render.cpp
    sources/systems/focus.cpp
    sources/systems/glyph_render.cpp
    sources/systems/hand_button.cpp
    sources/systems/hand_motion.cpp
    sources/systems/hand_pinch.cpp
    sources/systems/hand_poke.cpp
    sources/systems/hand_squeeze.cpp
    sources/systems/hand_thumb_rest.cpp
    sources/systems/hand_thumb_stick.cpp
    sources/systems/hand_trigger.cpp
    sources/systems/image_render.cpp
    sources/systems/keyboard_control.cpp
    sources/systems/layout.cpp
    sources/systems/line_render.cpp
    sources/systems/measure_glyph.cpp
    sources/systems/measure_model.cpp
    sources/systems/measure_text.cpp
    sources/systems/model_render.cpp
    sources/systems/mouse_button.cpp
    sources/systems/mouse_motion.cpp
    sources/systems/overlay.cpp
    sources/systems/rectangle_render.cpp
    sources/systems/ring_render.cpp
    sources/systems/scroll.cpp
    sources/systems/selection.cpp
    sources/systems/scrim_render.cpp
    sources/systems/shape_mesh.cpp
    sources/systems/text_field.cpp
    sources/systems/text_input.cpp
    sources/systems/text_render.cpp
    sources/theme.cpp
)
